# Generated by Django 5.1.3 on 2024-11-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Phone', 'Phone'), ('IT Equipment', 'IT Equipment'), ('Electronic', 'Electronic'), ('Furniture', 'Furniture')], max_length=50, null=True),
        ),
    ]
